spring.application.name=demo
notifService.value=email
#spring.h2.console.enable=true
#spring.datasource.url=jdbc:h2.file:C:\\Users\\Lenovo\\Downloads\\demo\\demo\\src\\main\\resources
spring.datasource.url=${DB_URL}
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable automatic execution of data.sql
spring.sql.init.mode=always

# Wait for Hibernate to create table schemas before running data.sql
spring.jpa.defer-datasource-initialization=true